// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/contracts/ory_polis.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderConfig) Reset() {
	*x = ProviderConfig{}
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfig) ProtoMessage() {}

func (x *ProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfig.ProtoReflect.Descriptor instead.
func (*ProviderConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ory_polis_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ProviderConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type OryPolisStepConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Values        *structpb.Struct       `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OryPolisStepConfig) Reset() {
	*x = OryPolisStepConfig{}
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OryPolisStepConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OryPolisStepConfig) ProtoMessage() {}

func (x *OryPolisStepConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OryPolisStepConfig.ProtoReflect.Descriptor instead.
func (*OryPolisStepConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ory_polis_proto_rawDescGZIP(), []int{1}
}

func (x *OryPolisStepConfig) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *OryPolisStepConfig) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

type OryPolisStepInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        *structpb.Struct       `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OryPolisStepInput) Reset() {
	*x = OryPolisStepInput{}
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OryPolisStepInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OryPolisStepInput) ProtoMessage() {}

func (x *OryPolisStepInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OryPolisStepInput.ProtoReflect.Descriptor instead.
func (*OryPolisStepInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ory_polis_proto_rawDescGZIP(), []int{2}
}

func (x *OryPolisStepInput) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

type OryPolisStepOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        *structpb.Struct       `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	StopPipeline  bool                   `protobuf:"varint,2,opt,name=stop_pipeline,json=stopPipeline,proto3" json:"stop_pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OryPolisStepOutput) Reset() {
	*x = OryPolisStepOutput{}
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OryPolisStepOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OryPolisStepOutput) ProtoMessage() {}

func (x *OryPolisStepOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OryPolisStepOutput.ProtoReflect.Descriptor instead.
func (*OryPolisStepOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ory_polis_proto_rawDescGZIP(), []int{3}
}

func (x *OryPolisStepOutput) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *OryPolisStepOutput) GetStopPipeline() bool {
	if x != nil {
		return x.StopPipeline
	}
	return false
}

type AuthProviderConfigOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthProviderConfigOption) Reset() {
	*x = AuthProviderConfigOption{}
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProviderConfigOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProviderConfigOption) ProtoMessage() {}

func (x *AuthProviderConfigOption) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProviderConfigOption.ProtoReflect.Descriptor instead.
func (*AuthProviderConfigOption) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ory_polis_proto_rawDescGZIP(), []int{4}
}

func (x *AuthProviderConfigOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AuthProviderConfigOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AuthProviderConfigOption) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AuthProviderConfigField struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	Key               string                      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label             string                      `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description       string                      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	HelpText          string                      `protobuf:"bytes,4,opt,name=help_text,json=helpText,proto3" json:"help_text,omitempty"`
	InputType         string                      `protobuf:"bytes,5,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	Secret            bool                        `protobuf:"varint,6,opt,name=secret,proto3" json:"secret,omitempty"`
	Required          bool                        `protobuf:"varint,7,opt,name=required,proto3" json:"required,omitempty"`
	Options           []*AuthProviderConfigOption `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`
	Lookup            string                      `protobuf:"bytes,9,opt,name=lookup,proto3" json:"lookup,omitempty"`
	ValidationPattern string                      `protobuf:"bytes,10,opt,name=validation_pattern,json=validationPattern,proto3" json:"validation_pattern,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthProviderConfigField) Reset() {
	*x = AuthProviderConfigField{}
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProviderConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProviderConfigField) ProtoMessage() {}

func (x *AuthProviderConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProviderConfigField.ProtoReflect.Descriptor instead.
func (*AuthProviderConfigField) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ory_polis_proto_rawDescGZIP(), []int{5}
}

func (x *AuthProviderConfigField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AuthProviderConfigField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AuthProviderConfigField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuthProviderConfigField) GetHelpText() string {
	if x != nil {
		return x.HelpText
	}
	return ""
}

func (x *AuthProviderConfigField) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *AuthProviderConfigField) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *AuthProviderConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *AuthProviderConfigField) GetOptions() []*AuthProviderConfigOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *AuthProviderConfigField) GetLookup() string {
	if x != nil {
		return x.Lookup
	}
	return ""
}

func (x *AuthProviderConfigField) GetValidationPattern() string {
	if x != nil {
		return x.ValidationPattern
	}
	return ""
}

type AuthProviderCapability struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Key              string                     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label            string                     `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Category         string                     `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description      string                     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Supported        bool                       `protobuf:"varint,5,opt,name=supported,proto3" json:"supported,omitempty"`
	DisabledReason   string                     `protobuf:"bytes,6,opt,name=disabled_reason,json=disabledReason,proto3" json:"disabled_reason,omitempty"`
	AppScopes        []string                   `protobuf:"bytes,7,rep,name=app_scopes,json=appScopes,proto3" json:"app_scopes,omitempty"`
	AdminReadScopes  []string                   `protobuf:"bytes,8,rep,name=admin_read_scopes,json=adminReadScopes,proto3" json:"admin_read_scopes,omitempty"`
	AdminWriteScopes []string                   `protobuf:"bytes,9,rep,name=admin_write_scopes,json=adminWriteScopes,proto3" json:"admin_write_scopes,omitempty"`
	ConfigFields     []*AuthProviderConfigField `protobuf:"bytes,10,rep,name=config_fields,json=configFields,proto3" json:"config_fields,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthProviderCapability) Reset() {
	*x = AuthProviderCapability{}
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProviderCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProviderCapability) ProtoMessage() {}

func (x *AuthProviderCapability) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProviderCapability.ProtoReflect.Descriptor instead.
func (*AuthProviderCapability) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ory_polis_proto_rawDescGZIP(), []int{6}
}

func (x *AuthProviderCapability) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AuthProviderCapability) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AuthProviderCapability) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AuthProviderCapability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuthProviderCapability) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *AuthProviderCapability) GetDisabledReason() string {
	if x != nil {
		return x.DisabledReason
	}
	return ""
}

func (x *AuthProviderCapability) GetAppScopes() []string {
	if x != nil {
		return x.AppScopes
	}
	return nil
}

func (x *AuthProviderCapability) GetAdminReadScopes() []string {
	if x != nil {
		return x.AdminReadScopes
	}
	return nil
}

func (x *AuthProviderCapability) GetAdminWriteScopes() []string {
	if x != nil {
		return x.AdminWriteScopes
	}
	return nil
}

func (x *AuthProviderCapability) GetConfigFields() []*AuthProviderConfigField {
	if x != nil {
		return x.ConfigFields
	}
	return nil
}

type AuthProviderDescriptor struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Id             string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label          string                    `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description    string                    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Categories     []string                  `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	Implementation string                    `protobuf:"bytes,5,opt,name=implementation,proto3" json:"implementation,omitempty"`
	Version        string                    `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	DocsUrl        string                    `protobuf:"bytes,7,opt,name=docs_url,json=docsUrl,proto3" json:"docs_url,omitempty"`
	SupportLevel   string                    `protobuf:"bytes,8,opt,name=support_level,json=supportLevel,proto3" json:"support_level,omitempty"`
	DisabledReason string                    `protobuf:"bytes,9,opt,name=disabled_reason,json=disabledReason,proto3" json:"disabled_reason,omitempty"`
	Capabilities   []*AuthProviderCapability `protobuf:"bytes,10,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthProviderDescriptor) Reset() {
	*x = AuthProviderDescriptor{}
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProviderDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProviderDescriptor) ProtoMessage() {}

func (x *AuthProviderDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProviderDescriptor.ProtoReflect.Descriptor instead.
func (*AuthProviderDescriptor) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ory_polis_proto_rawDescGZIP(), []int{7}
}

func (x *AuthProviderDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthProviderDescriptor) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AuthProviderDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuthProviderDescriptor) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *AuthProviderDescriptor) GetImplementation() string {
	if x != nil {
		return x.Implementation
	}
	return ""
}

func (x *AuthProviderDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AuthProviderDescriptor) GetDocsUrl() string {
	if x != nil {
		return x.DocsUrl
	}
	return ""
}

func (x *AuthProviderDescriptor) GetSupportLevel() string {
	if x != nil {
		return x.SupportLevel
	}
	return ""
}

func (x *AuthProviderDescriptor) GetDisabledReason() string {
	if x != nil {
		return x.DisabledReason
	}
	return ""
}

func (x *AuthProviderDescriptor) GetCapabilities() []*AuthProviderCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type AuthProviderDescribeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthProviderDescribeConfig) Reset() {
	*x = AuthProviderDescribeConfig{}
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProviderDescribeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProviderDescribeConfig) ProtoMessage() {}

func (x *AuthProviderDescribeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProviderDescribeConfig.ProtoReflect.Descriptor instead.
func (*AuthProviderDescribeConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ory_polis_proto_rawDescGZIP(), []int{8}
}

func (x *AuthProviderDescribeConfig) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AuthProviderDescribeConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

type AuthProviderDescribeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthProviderDescribeInput) Reset() {
	*x = AuthProviderDescribeInput{}
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProviderDescribeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProviderDescribeInput) ProtoMessage() {}

func (x *AuthProviderDescribeInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProviderDescribeInput.ProtoReflect.Descriptor instead.
func (*AuthProviderDescribeInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ory_polis_proto_rawDescGZIP(), []int{9}
}

func (x *AuthProviderDescribeInput) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AuthProviderDescribeInput) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

type AuthProviderDescribeOutput struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Providers     []*AuthProviderDescriptor `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthProviderDescribeOutput) Reset() {
	*x = AuthProviderDescribeOutput{}
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProviderDescribeOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProviderDescribeOutput) ProtoMessage() {}

func (x *AuthProviderDescribeOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ory_polis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProviderDescribeOutput.ProtoReflect.Descriptor instead.
func (*AuthProviderDescribeOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ory_polis_proto_rawDescGZIP(), []int{10}
}

func (x *AuthProviderDescribeOutput) GetProviders() []*AuthProviderDescriptor {
	if x != nil {
		return x.Providers
	}
	return nil
}

var File_internal_contracts_ory_polis_proto protoreflect.FileDescriptor

const file_internal_contracts_ory_polis_proto_rawDesc = "" +
	"\n" +
	"\"internal/contracts/ory_polis.proto\x12\x1dworkflow.plugins.ory_polis.v1\x1a\x1cgoogle/protobuf/struct.proto\"D\n" +
	"\x0eProviderConfig\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"]\n" +
	"\x12OryPolisStepConfig\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12/\n" +
	"\x06values\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06values\"D\n" +
	"\x11OryPolisStepInput\x12/\n" +
	"\x06values\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06values\"j\n" +
	"\x12OryPolisStepOutput\x12/\n" +
	"\x06values\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06values\x12#\n" +
	"\rstop_pipeline\x18\x02 \x01(\bR\fstopPipeline\"h\n" +
	"\x18AuthProviderConfigOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xed\x02\n" +
	"\x17AuthProviderConfigField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\thelp_text\x18\x04 \x01(\tR\bhelpText\x12\x1d\n" +
	"\n" +
	"input_type\x18\x05 \x01(\tR\tinputType\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\bR\x06secret\x12\x1a\n" +
	"\brequired\x18\a \x01(\bR\brequired\x12Q\n" +
	"\aoptions\x18\b \x03(\v27.workflow.plugins.ory_polis.v1.AuthProviderConfigOptionR\aoptions\x12\x16\n" +
	"\x06lookup\x18\t \x01(\tR\x06lookup\x12-\n" +
	"\x12validation_pattern\x18\n" +
	" \x01(\tR\x11validationPattern\"\x9b\x03\n" +
	"\x16AuthProviderCapability\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tsupported\x18\x05 \x01(\bR\tsupported\x12'\n" +
	"\x0fdisabled_reason\x18\x06 \x01(\tR\x0edisabledReason\x12\x1d\n" +
	"\n" +
	"app_scopes\x18\a \x03(\tR\tappScopes\x12*\n" +
	"\x11admin_read_scopes\x18\b \x03(\tR\x0fadminReadScopes\x12,\n" +
	"\x12admin_write_scopes\x18\t \x03(\tR\x10adminWriteScopes\x12[\n" +
	"\rconfig_fields\x18\n" +
	" \x03(\v26.workflow.plugins.ory_polis.v1.AuthProviderConfigFieldR\fconfigFields\"\x86\x03\n" +
	"\x16AuthProviderDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\x12&\n" +
	"\x0eimplementation\x18\x05 \x01(\tR\x0eimplementation\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x19\n" +
	"\bdocs_url\x18\a \x01(\tR\adocsUrl\x12#\n" +
	"\rsupport_level\x18\b \x01(\tR\fsupportLevel\x12'\n" +
	"\x0fdisabled_reason\x18\t \x01(\tR\x0edisabledReason\x12Y\n" +
	"\fcapabilities\x18\n" +
	" \x03(\v25.workflow.plugins.ory_polis.v1.AuthProviderCapabilityR\fcapabilities\"X\n" +
	"\x1aAuthProviderDescribeConfig\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\"W\n" +
	"\x19AuthProviderDescribeInput\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\"q\n" +
	"\x1aAuthProviderDescribeOutput\x12S\n" +
	"\tproviders\x18\x01 \x03(\v25.workflow.plugins.ory_polis.v1.AuthProviderDescriptorR\tprovidersBEZCgithub.com/GoCodeAlone/workflow-plugin-ory-polis/internal/contractsb\x06proto3"

var (
	file_internal_contracts_ory_polis_proto_rawDescOnce sync.Once
	file_internal_contracts_ory_polis_proto_rawDescData []byte
)

func file_internal_contracts_ory_polis_proto_rawDescGZIP() []byte {
	file_internal_contracts_ory_polis_proto_rawDescOnce.Do(func() {
		file_internal_contracts_ory_polis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_ory_polis_proto_rawDesc), len(file_internal_contracts_ory_polis_proto_rawDesc)))
	})
	return file_internal_contracts_ory_polis_proto_rawDescData
}

var file_internal_contracts_ory_polis_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_contracts_ory_polis_proto_goTypes = []any{
	(*ProviderConfig)(nil),             // 0: workflow.plugins.ory_polis.v1.ProviderConfig
	(*OryPolisStepConfig)(nil),         // 1: workflow.plugins.ory_polis.v1.OryPolisStepConfig
	(*OryPolisStepInput)(nil),          // 2: workflow.plugins.ory_polis.v1.OryPolisStepInput
	(*OryPolisStepOutput)(nil),         // 3: workflow.plugins.ory_polis.v1.OryPolisStepOutput
	(*AuthProviderConfigOption)(nil),   // 4: workflow.plugins.ory_polis.v1.AuthProviderConfigOption
	(*AuthProviderConfigField)(nil),    // 5: workflow.plugins.ory_polis.v1.AuthProviderConfigField
	(*AuthProviderCapability)(nil),     // 6: workflow.plugins.ory_polis.v1.AuthProviderCapability
	(*AuthProviderDescriptor)(nil),     // 7: workflow.plugins.ory_polis.v1.AuthProviderDescriptor
	(*AuthProviderDescribeConfig)(nil), // 8: workflow.plugins.ory_polis.v1.AuthProviderDescribeConfig
	(*AuthProviderDescribeInput)(nil),  // 9: workflow.plugins.ory_polis.v1.AuthProviderDescribeInput
	(*AuthProviderDescribeOutput)(nil), // 10: workflow.plugins.ory_polis.v1.AuthProviderDescribeOutput
	(*structpb.Struct)(nil),            // 11: google.protobuf.Struct
}
var file_internal_contracts_ory_polis_proto_depIdxs = []int32{
	11, // 0: workflow.plugins.ory_polis.v1.OryPolisStepConfig.values:type_name -> google.protobuf.Struct
	11, // 1: workflow.plugins.ory_polis.v1.OryPolisStepInput.values:type_name -> google.protobuf.Struct
	11, // 2: workflow.plugins.ory_polis.v1.OryPolisStepOutput.values:type_name -> google.protobuf.Struct
	4,  // 3: workflow.plugins.ory_polis.v1.AuthProviderConfigField.options:type_name -> workflow.plugins.ory_polis.v1.AuthProviderConfigOption
	5,  // 4: workflow.plugins.ory_polis.v1.AuthProviderCapability.config_fields:type_name -> workflow.plugins.ory_polis.v1.AuthProviderConfigField
	6,  // 5: workflow.plugins.ory_polis.v1.AuthProviderDescriptor.capabilities:type_name -> workflow.plugins.ory_polis.v1.AuthProviderCapability
	7,  // 6: workflow.plugins.ory_polis.v1.AuthProviderDescribeOutput.providers:type_name -> workflow.plugins.ory_polis.v1.AuthProviderDescriptor
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_internal_contracts_ory_polis_proto_init() }
func file_internal_contracts_ory_polis_proto_init() {
	if File_internal_contracts_ory_polis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_ory_polis_proto_rawDesc), len(file_internal_contracts_ory_polis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_ory_polis_proto_goTypes,
		DependencyIndexes: file_internal_contracts_ory_polis_proto_depIdxs,
		MessageInfos:      file_internal_contracts_ory_polis_proto_msgTypes,
	}.Build()
	File_internal_contracts_ory_polis_proto = out.File
	file_internal_contracts_ory_polis_proto_goTypes = nil
	file_internal_contracts_ory_polis_proto_depIdxs = nil
}
